-- MySQL Script generated by MySQL Workbench
-- Wed Jul 22 17:24:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Database `db_rfid`
-- -----------------------------------------------------
CREATE OR REPLACE DATABASE `db_rfid`;
USE `db_rfid`;

-- -----------------------------------------------------
-- Table `tb_cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_cadastro` (
  `id_cadastro` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Indentificador do cadastro.',
  `no_usuario` VARCHAR(45) NOT NULL COMMENT 'Nome do usuário cadastrado.',
  `cd_cartao` VARCHAR(25) NOT NULL COMMENT 'Código do cartão do usuário.',
  PRIMARY KEY (`id_cadastro`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_cadastro_UNIQUE` ON `tb_cadastro` (`id_cadastro` ASC);


-- -----------------------------------------------------
-- Table `tb_dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_dispositivo` (
  `id_dispositivo` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Idendificador do dispositivo.',
  `no_dispositivo` VARCHAR(15) NOT NULL COMMENT 'Descrição do dispositivo.',
  `no_localizacao` VARCHAR(45) NOT NULL COMMENT 'Localização do dispositivo.',
  `vl_andar` INT(3) NOT NULL COMMENT 'O andar em que se encontra o dispositivo.',
  `st_ativo` CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'Status ativo ou inativo do dispositivo.',
  PRIMARY KEY (`id_dispositivo`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_dispositivo_UNIQUE` ON `tb_dispositivo` (`id_dispositivo` ASC);


-- -----------------------------------------------------
-- Table `tb_ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_ocorrencia` (
  `id_ocorrencia` INT UNSIGNED NOT NULL COMMENT 'Identificador da ocorrência.',
  `id_dispositivo` INT UNSIGNED NOT NULL COMMENT 'Identificador do dispositivo.',
  `id_cadastro` INT UNSIGNED NOT NULL COMMENT 'Identificador do cadastro.',
  `dt_ocorrencia` DATE NOT NULL COMMENT 'Data em que houve a detecção de um movimento.',
  `hr_ocorrencia` TIME NOT NULL COMMENT 'Hora em que houve a detecção de um movimento.',
  `st_ocorrencia` CHAR(1) NOT NULL COMMENT 'Se o movimento foi de \'entrada\' ou \'saída\'.',
  PRIMARY KEY (`id_ocorrencia`),
  CONSTRAINT `fk_tb_ocorrencia_tb_dispositivo1`
    FOREIGN KEY (`id_dispositivo`)
    REFERENCES `tb_dispositivo` (`id_dispositivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_ocorrencia_cadastro1`
    FOREIGN KEY (`id_cadastro`)
    REFERENCES `tb_cadastro` (`id_cadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_ocorrencia_UNIQUE` ON `tb_ocorrencia` (`id_ocorrencia` ASC);

CREATE INDEX `fk_tb_ocorrencia_tb_dispositivo1_idx` ON `tb_ocorrencia` (`id_dispositivo` ASC);

CREATE INDEX `fk_tb_ocorrencia_cadastro1_idx` ON `tb_ocorrencia` (`id_cadastro` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
