-- MySQL Script generated by MySQL Workbench
-- Wed Jul 29 16:19:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Database `db_rfid`
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `db_rfid`;
CREATE DATABASE `db_rfid`;
USE `db_rfid`;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `tb_cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_cadastro` (
  `id_cadastro` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Indentificador do cadastro.',
  `no_usuario` VARCHAR(45) NOT NULL COMMENT 'Nome do usuário cadastrado.',
  `ed_arquivo_imagem` VARCHAR(50) NULL COMMENT 'Endereço no servidor da imagem do usuário.',
  PRIMARY KEY (`id_cadastro`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_cadastro_UNIQUE` ON `tb_cadastro` (`id_cadastro` ASC);


-- -----------------------------------------------------
-- Table `tb_dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_dispositivo` (
  `id_dispositivo` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Idendificador do dispositivo.',
  `no_dispositivo` VARCHAR(15) NOT NULL COMMENT 'Descrição do dispositivo.',
  `no_localizacao` VARCHAR(45) NOT NULL COMMENT 'Localização do dispositivo.',
  `vl_andar` INT(3) NOT NULL COMMENT 'O andar em que se encontra o dispositivo.',
  `st_ativo` CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'Status ativo ou inativo do dispositivo.',
  PRIMARY KEY (`id_dispositivo`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_dispositivo_UNIQUE` ON `tb_dispositivo` (`id_dispositivo` ASC);


-- -----------------------------------------------------
-- Table `tb_ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_ocorrencia` (
  `id_ocorrencia` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identificador da ocorrência.',
  `id_dispositivo` INT UNSIGNED NOT NULL COMMENT 'Identificador do dispositivo.',
  `id_cadastro` INT UNSIGNED NOT NULL COMMENT 'Identificador do cadastro.',
  `dt_ocorrencia` DATE NOT NULL COMMENT 'Data em que houve a detecção de um movimento.',
  `hr_ocorrencia` TIME NOT NULL COMMENT 'Hora em que houve a detecção de um movimento.',
  `st_ocorrencia` CHAR(1) NOT NULL DEFAULT 'S' COMMENT 'Se o movimento foi de \'entrada\' ou \'saída\'.',
  PRIMARY KEY (`id_ocorrencia`),
  CONSTRAINT `fk_tb_ocorrencia_tb_dispositivo1`
    FOREIGN KEY (`id_dispositivo`)
    REFERENCES `tb_dispositivo` (`id_dispositivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_ocorrencia_cadastro1`
    FOREIGN KEY (`id_cadastro`)
    REFERENCES `tb_cadastro` (`id_cadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_ocorrencia_UNIQUE` ON `tb_ocorrencia` (`id_ocorrencia` ASC);

CREATE INDEX `fk_tb_ocorrencia_tb_dispositivo1_idx` ON `tb_ocorrencia` (`id_dispositivo` ASC);

CREATE INDEX `fk_tb_ocorrencia_cadastro1_idx` ON `tb_ocorrencia` (`id_cadastro` ASC);


-- -----------------------------------------------------
-- Table `tb_cartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_cartao` (
  `id_cartao` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Indentificador do cartão.',
  `no_cartao` VARCHAR(10) NOT NULL COMMENT 'Tag RFID do cartão.',
  PRIMARY KEY (`id_cartao`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_cartao_UNIQUE` ON `tb_cartao` (`id_cartao` ASC);

CREATE UNIQUE INDEX `no_cartao_UNIQUE` ON `tb_cartao` (`no_cartao` ASC);


-- -----------------------------------------------------
-- Table `tb_cadastro_cartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_cadastro_cartao` (
  `id_cadastro_cartao` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador da associação entre cadastro e cartão.',
  `id_cadastro` INT UNSIGNED NOT NULL COMMENT 'Identificador do cadastro.',
  `id_cartao` INT UNSIGNED NOT NULL COMMENT 'Identificador do cartão.',
  `st_estado` CHAR(1) NOT NULL COMMENT 'Indica se o cartão está ativo ou inativo\n',
  PRIMARY KEY (`id_cadastro_cartao`),
  CONSTRAINT `fk_tb_cadastro_cartao_tb_cadastro1`
    FOREIGN KEY (`id_cadastro`)
    REFERENCES `tb_cadastro` (`id_cadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_cadastro_cartao_tb_cartao1`
    FOREIGN KEY (`id_cartao`)
    REFERENCES `tb_cartao` (`id_cartao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tb_cadastro_cartao_tb_cadastro1_idx` ON `tb_cadastro_cartao` (`id_cadastro` ASC);

CREATE INDEX `fk_tb_cadastro_cartao_tb_cartao1_idx` ON `tb_cadastro_cartao` (`id_cartao` ASC);

CREATE UNIQUE INDEX `id_cadastro_cartao_UNIQUE` ON `tb_cadastro_cartao` (`id_cadastro_cartao` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
